// Health facilities dataset for HB Tracker.
//
// IMPORTANT: This is a SEED dataset compiled from public sources.
// The pilot nurse should verify each entry's name, location, phone, and
// services before relying on it during pilot deployment.
//
// To add a new facility, copy the structure below.
// Coordinates: latitude, longitude in decimal degrees.
//   - You can get a coordinate by long-pressing on Google Maps,
//     then copying the numbers shown (e.g. 5.0699, -1.7411).
// Type: 'CHPS', 'Health Centre', 'Clinic', 'Hospital', 'District Hospital',
//       'Regional Hospital', 'Teaching Hospital', 'Maternity Home', 'Polyclinic'
// Phone: international format with leading + (or empty string '' if unknown).
// Verified: 'verified' once a nurse has checked it; 'unverified' otherwise.
// LastChecked: YYYY-MM-DD when last verified, or null.

export const FACILITIES = [
  // ===== Western Region — Mpohor and surrounding districts =====
  {
    id: 'wr-mp-001',
    name: 'Mpohor District Hospital',
    type: 'District Hospital',
    region: 'Western',
    district: 'Mpohor',
    town: 'Mpohor',
    lat: 5.0167, lng: -1.8833,
    phone: '',
    services: 'General OPD, Antenatal, Delivery, Inpatient',
    notes: '',
    verified: 'verified', lastChecked: 2026-04-25,
  },
  {
    id: 'wr-mp-002',
    name: 'Daboase Health Centre',
    type: 'Health Centre',
    region: 'Western',
    district: 'Mpohor',
    town: 'Daboase',
    lat: 5.1500, lng: -1.7333,
    phone: '',
    services: 'OPD, Antenatal, Family Planning',
    notes: '',
    verified: 'verified', lastChecked: 2026-04-25,
  },
  {
    id: 'wr-mp-003',
    name: 'Adum Banso Health Center',
    type: 'CHPS',
    region: 'Western',
    district: 'Mpohor',
    town: 'Adum Banso',
    lat: 5.0500, lng: -1.8500,
    phone: '',
    services: 'Basic OPD, Antenatal home visits, Outreach',
    notes: '',
    verified: 'verified', lastChecked: 2026-04-25,
  },
  {
    id: 'wr-ahw-001',
    name: 'Agona Nkwanta Health Centre',
    type: 'Health Centre',
    region: 'Western',
    district: 'Ahanta West',
    town: 'Agona Nkwanta',
    lat: 4.8833, lng: -1.9667,
    phone: '',
    services: 'OPD, Antenatal, Maternity',
    notes: '',
    verified: 'unverified', lastChecked: null,
  },
  {
    id: 'wr-tar-001',
    name: 'Tarkwa Municipal Hospital',
    type: 'District Hospital',
    region: 'Western',
    district: 'Tarkwa-Nsuaem',
    town: 'Tarkwa',
    lat: 5.3000, lng: -1.9833,
    phone: '',
    services: 'General, Surgery, Antenatal, Delivery, Lab',
    notes: '',
    verified: 'unverified', lastChecked: null,
  },
  {
    id: 'wr-shm-001',
    name: 'Effia-Nkwanta Regional Hospital',
    type: 'Regional Hospital',
    region: 'Western',
    district: 'Sekondi-Takoradi',
    town: 'Sekondi',
    lat: 4.9333, lng: -1.7167,
    phone: '',
    services: 'Regional referral — full obstetric services, blood transfusion',
    notes: 'Use for serious referrals from Mpohor district.',
    verified: 'unverified', lastChecked: null,
  },
  {
    id: 'wr-shm-002',
    name: 'Takoradi Hospital (European)',
    type: 'Hospital',
    region: 'Western',
    district: 'Sekondi-Takoradi',
    town: 'Takoradi',
    lat: 4.9000, lng: -1.7600,
    phone: '',
    services: 'General, Maternity',
    notes: '',
    verified: 'unverified', lastChecked: null,
  },
  {
    id: 'wr-pre-001',
    name: 'Prestea Government Hospital',
    type: 'District Hospital',
    region: 'Western',
    district: 'Prestea-Huni Valley',
    town: 'Prestea',
    lat: 5.4333, lng: -2.1500,
    phone: '',
    services: 'General, Antenatal, Delivery',
    notes: '',
    verified: 'unverified', lastChecked: null,
  },
  {
    id: 'wr-elu-001',
    name: 'Elubo Health Centre',
    type: 'Health Centre',
    region: 'Western',
    district: 'Jomoro',
    town: 'Elubo',
    lat: 5.1167, lng: -2.7833,
    phone: '',
    services: 'OPD, Antenatal',
    notes: '',
    verified: 'unverified', lastChecked: null,
  },

  // ===== Greater Accra — for women who travel =====
  {
    id: 'ga-acc-001',
    name: 'Korle Bu Teaching Hospital',
    type: 'Teaching Hospital',
    region: 'Greater Accra',
    district: 'Accra Metro',
    town: 'Accra',
    lat: 5.5380, lng: -0.2310,
    phone: '',
    services: 'Tertiary referral — all specialties, blood services, NICU',
    notes: 'National referral hospital.',
    verified: 'unverified', lastChecked: null,
  },
  {
    id: 'ga-acc-002',
    name: 'Ridge Hospital',
    type: 'Regional Hospital',
    region: 'Greater Accra',
    district: 'Accra Metro',
    town: 'Accra',
    lat: 5.5667, lng: -0.1833,
    phone: '',
    services: 'General, Obstetric emergencies, Surgery',
    notes: '',
    verified: 'unverified', lastChecked: null,
  },

  // ===== Ashanti — Kumasi =====
  {
    id: 'as-kum-001',
    name: 'Komfo Anokye Teaching Hospital',
    type: 'Teaching Hospital',
    region: 'Ashanti',
    district: 'Kumasi Metro',
    town: 'Kumasi',
    lat: 6.6986, lng: -1.6244,
    phone: '',
    services: 'Tertiary referral — all specialties, blood services, NICU',
    notes: 'Major referral for Ashanti and northern regions.',
    verified: 'unverified', lastChecked: null,
  },

  // ===== Central — Cape Coast =====
  {
    id: 'cr-cap-001',
    name: 'Cape Coast Teaching Hospital',
    type: 'Teaching Hospital',
    region: 'Central',
    district: 'Cape Coast Metro',
    town: 'Cape Coast',
    lat: 5.1167, lng: -1.2833,
    phone: '',
    services: 'Tertiary care, Obstetrics, NICU',
    notes: '',
    verified: 'unverified', lastChecked: null,
  },
]
